In [1]:
### Borough_Meansr_With_Avg-to_Max.ipynb ( adds Avg_to_Max column)

import pandas as pd
import matplotlib.pyplot as plt 
import numpy as np

     
df = pd.read_csv("Boroughs_Meansr.csv")

df = df.drop(df.loc[:, df.columns.str.contains('Unnamed: 0') ], axis=1,inplace=False)
df.columns = ['Boroughs', 'Avg_Over_20_Yrs']
print(df, '<-- print df...................')

column = df["Avg_Over_20_Yrs"]
max_value = column.max()
print(max_value, '<--print(max_value...........')
print(column, '<--print(column.................')

df["Avg_To_max"] = column/max_value

print(df, '<-- print df...................')

df.to_csv("Boroughs_Meansr_With_Avg_To_max.csv")

                Boroughs  Avg_Over_20_Yrs
0   Kensington & Chelsea         602028.0
1            Westminster         429966.0
2                 Camden         378834.0
3   Hammersmith & Fulham         369030.0
4         City of London         330346.0
5   Richmond upon Thames         316164.0
6              Islington         295528.0
7             Wandsworth         278677.0
8           Inner London         251886.0
9                 Barnet         251429.0
10              Haringey         232658.0
11  Kingston upon Thames         232175.0
12                Merton         227012.0
13                Ealing         225522.0
14                Harrow         224015.0
15               Lambeth         222909.0
16               Hackney         222097.0
17             Southwark         218883.0
18                 Brent         218881.0
19                LONDON         215671.0
20         Tower Hamlets         211160.0
21               Bromley         210814.0
22              Hounslow         197929.0
23          Outer London         196262.0
24             Redbridge         194550.0
25            Hillingdon         192474.0
26               Enfield         184059.0
27                Sutton         180631.0
28               Croydon         172950.0
29             Greenwich         172371.0
30        Waltham Forest         171310.0
31              Lewisham         171133.0
32              Havering         169631.0
33            SOUTH EAST         168261.0
34                Newham         157800.0
35                Bexley         156231.0
36       EAST OF ENGLAND         145312.0
37            SOUTH WEST         143703.0
38               England         132795.0
39    Barking & Dagenham         130122.0
40         WEST MIDLANDS         113183.0
41         EAST MIDLANDS         107305.0
42    YORKS & THE HUMBER          97855.0
43            NORTH WEST          97566.0
44            NORTH EAST          89821.0 <-- print df...................
602028.0 <--print(max_value...........
0     602028.0
1     429966.0
2     378834.0
3     369030.0
4     330346.0
5     316164.0
6     295528.0
7     278677.0
8     251886.0
9     251429.0
10    232658.0
11    232175.0
12    227012.0
13    225522.0
14    224015.0
15    222909.0
16    222097.0
17    218883.0
18    218881.0
19    215671.0
20    211160.0
21    210814.0
22    197929.0
23    196262.0
24    194550.0
25    192474.0
26    184059.0
27    180631.0
28    172950.0
29    172371.0
30    171310.0
31    171133.0
32    169631.0
33    168261.0
34    157800.0
35    156231.0
36    145312.0
37    143703.0
38    132795.0
39    130122.0
40    113183.0
41    107305.0
42     97855.0
43     97566.0
44     89821.0
Name: Avg_Over_20_Yrs, dtype: float64 <--print(column.................
                Boroughs  Avg_Over_20_Yrs  Avg_To_max
0   Kensington & Chelsea         602028.0    1.000000
1            Westminster         429966.0    0.714196
2                 Camden         378834.0    0.629263
3   Hammersmith & Fulham         369030.0    0.612978
4         City of London         330346.0    0.548722
5   Richmond upon Thames         316164.0    0.525165
6              Islington         295528.0    0.490887
7             Wandsworth         278677.0    0.462897
8           Inner London         251886.0    0.418396
9                 Barnet         251429.0    0.417637
10              Haringey         232658.0    0.386457
11  Kingston upon Thames         232175.0    0.385655
12                Merton         227012.0    0.377079
13                Ealing         225522.0    0.374604
14                Harrow         224015.0    0.372101
15               Lambeth         222909.0    0.370264
16               Hackney         222097.0    0.368915
17             Southwark         218883.0    0.363576
18                 Brent         218881.0    0.363573
19                LONDON         215671.0    0.358241
20         Tower Hamlets         211160.0    0.350748
21               Bromley         210814.0    0.350173
22              Hounslow         197929.0    0.328770
23          Outer London         196262.0    0.326001
24             Redbridge         194550.0    0.323158
25            Hillingdon         192474.0    0.319709
26               Enfield         184059.0    0.305732
27                Sutton         180631.0    0.300038
28               Croydon         172950.0    0.287279
29             Greenwich         172371.0    0.286317
30        Waltham Forest         171310.0    0.284555
31              Lewisham         171133.0    0.284261
32              Havering         169631.0    0.281766
33            SOUTH EAST         168261.0    0.279490
34                Newham         157800.0    0.262114
35                Bexley         156231.0    0.259508
36       EAST OF ENGLAND         145312.0    0.241371
37            SOUTH WEST         143703.0    0.238698
38               England         132795.0    0.220579
39    Barking & Dagenham         130122.0    0.216139
40         WEST MIDLANDS         113183.0    0.188003
41         EAST MIDLANDS         107305.0    0.178239
42    YORKS & THE HUMBER          97855.0    0.162542
43            NORTH WEST          97566.0    0.162062
44            NORTH EAST          89821.0    0.149197 <-- print df...................